AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local ucsg project to get all users' buildings

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . # format is projectPath/
      Handler: lambda_function.lambda_handler # format is filename.functionName
      Runtime: python3.8